#! /bin/sh

OS=$(uname)

# MIT License
#
# Copyright (c) 2022 Thomas Will <thomas@xinux.de>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

USAGE="check_zfs_snapshot_retention v$VERSION
Copyright (c)  \
Thomas Will <thomas@xinux.de>


$SHORT_DESCRIPTION


Usage: check_zfs_snapshot_retention <options>

Options:
 -c, --critical=OPT_CRITICAL
   critical COUNT of retention  
 -d, --dataset=OPT_DATASET
    The ZFS dataset to check.
 -h, --help
    Show this help.
 -S, --snapshotname=Snapshotname
    Name of the snapshot to grep for
 -s, --short-description
    Show a short description of the command.
 -v, --version
    Show the version number.
 -w, --warning=OPT_WARNING
   warning COUNT of retention  

"

# Exit codes
STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

# Defaults
OPT_SNAPSHOTNAME="@"


_getopts() {
	while getopts ':c:d:hS:svw:-:' OPT ; do
		case $OPT in

			c)
				OPT_CRITICAL=$(( OPTARG ))
			;;

			d)
				OPT_DATASET="$OPTARG"
				;;

			h)
				echo "$USAGE"
				exit 0
				;;

			S)
				OPT_SNAPSHOTNAME="$OPTARG"
				;;
			s)
				echo "$SHORT_DESCRIPTION"
				exit 0
				;;

			v)
				echo "$VERSION"
				exit 0
				;;

			w)
				OPT_WARNING=$((  OPTARG ))
				;;

			\?)
				echo "Invalid option “-$OPTARG”!" >&2
				exit 2
				;;

			:)
				echo "Option “-$OPTARG” requires an argument!" >&2
				exit 3
				;;

			-)
				LONG_OPTARG="${OPTARG#*=}"

				case $OPTARG in

					critical=?*)
						OPT_CRITICAL=$(( LONG_OPTARG ))
						;;

					dataset=?*)
						OPT_DATASET="$LONG_OPTARG"
						;;

					help)
						echo "$USAGE"
						exit 0
						;;

					snapshotname=?*)
						OPT_SNAPSHOTNAME="$LONG_OPTARG"
						;;

					short-description)
						echo "$SHORT_DESCRIPTION"
						exit 0
						;;

					version)
						echo "$VERSION"
						exit 0
						;;

					warning=?*)
						OPT_WARNING=$((  LONG_OPTARG ))
						;;

					critical*|dataset*|warning*)
						echo "Option “--$OPTARG” requires an argument!" >&2
						exit 3
						;;

					help*|short-description*|version*)
						echo "No argument allowed for the option “--$OPTARG”!" >&2
						exit 4
						;;

					'')	# "--" terminates argument processing
						break
						;;

					*)
						echo "Invalid option “--$OPTARG”!" >&2
						exit 2
						;;

				esac
				;;

		esac
	done
}

_snapshot_count() {
	local COUNT
	COUNT="$(zfs get -Hpr -t snapshot creation "$1" | grep $OPT_SNAPSHOTNAME | wc -l)"
	echo $COUNT
}


_getopts $@

if [ -z "$OPT_WARNING" ]; then
	# 1 day
	OPT_WARNING=86400
fi

if [ -z "$OPT_CRITICAL" ]; then
	# 3 day
	OPT_CRITICAL=259200
fi

if [ -z "$OPT_DATASET" ]; then
	echo "Dataset has to be set! Use option -d <dataset>" >&2
	echo "$USAGE" >&2
	exit $STATE_UNKNOWN
fi

if ! zfs list "$OPT_DATASET" > /dev/null 2>&1; then
	echo "'$OPT_DATASET' is no ZFS dataset!" >&2
	echo "$USAGE" >&2
	exit $STATE_UNKNOWN
fi


if [ "$OPT_WARNING" -lt "$OPT_CRITICAL" ]; then
	echo '-w OPT_WARNING must be greater than -c OPT_CRITICAL'
	_usage >&2
	exit $STATE_UNKNOWN
fi

RETURN=STATE_UNKNOWN


COUNT=$(_snapshot_count "$OPT_DATASET")

if [ "$COUNT" -lt "$OPT_CRITICAL" ]; then
	RETURN=$STATE_CRITICAL
	MESSAGE="CRITICAL:"
elif [ "$COUNT" -lt "$OPT_WARNING" ]; then
	RETURN=$STATE_WARNING
	MESSAGE="WARNING:"
else
	RETURN=$STATE_OK
	MESSAGE="OK:"
fi

#DATE="$(_timestamp_to_datetime "$CREATION_DATE")"

echo "$MESSAGE Retention Count was $COUNT for '$OPT_DATASET'" 
#echo "$MESSAGE Last snapshot for dataset '$OPT_DATASET' was created on $DATE $(_performance_data)"
exit $RETURN
